# SPDX-FileCopyrightText: 2026 Olivier Ami
# SPDX-License-Identifier: Apache-2.0 OR MIT
"""Generate the deterministic CycloneDX E1 native-core source SBOM."""

from __future__ import annotations

import argparse
import fnmatch
import hashlib
import json
import os
import re
import secrets
import stat
import sys
import urllib.parse
import uuid
from collections.abc import Callable
from datetime import date
from pathlib import Path, PurePosixPath
from typing import Any

PROFILE = "e1-native-core"
PROJECT_VERSION = "0.0.1"
MANIFEST_LICENSE = "CC-BY-4.0"
SELF_ARTIFACT_ID = "sbom-engine-e1-native-core"
MANIFEST_RELATIVE = "artifacts/e1/manifest.json"
OUTPUT_RELATIVE = "artifacts/sbom/engine-e1-native-core.cdx.json"
SAFE_INTEGER_MAX = 9_007_199_254_740_991
MANIFEST_FIELDS = {
    "schema_version",
    "project",
    "generated_at",
    "manifest_document_license",
    "hash_algorithm",
    "artifacts",
}
EXPECTED_ARTIFACTS = {
    "e1-native-core-report": {
        "kind": "evidence-report",
        "path": "docs/engine/evidence/E1_NATIVE_CORE_REPORT.md",
        "media_type": "text/markdown",
        "license_expression": "CC-BY-4.0",
        "provenance": (
            "Generated from local executions and GitHub Actions results for native "
            "source bbf84cb806d95701daa2887e71d90a819c4a4c83 and corrective "
            "evidence sources 0e1f6cf45b7b4d0721fc9fb94cb9b1582b7e5b41 and "
            "4db5c7436a8139d227de58d5f5ff7280e8a0f9ea"
        ),
        "verification_status": "PASS",
        "note": (
            "The artifact is hash-verified; its content retains the initial hosted "
            "FAIL, corrective hosted PASS, and final evidence-head report NOT_RUN"
        ),
    },
    "adr-018-canonical-json-posix-cas": {
        "kind": "architecture-decision-record",
        "path": "spec/adr/ADR-018-canonical-json-profile-posix-cas.md",
        "media_type": "text/markdown",
        "license_expression": "CC-BY-4.0",
        "provenance": (
            "Accepted decision for the bounded E1 internal native-core implementation"
        ),
        "verification_status": "PASS",
    },
    SELF_ARTIFACT_ID: {
        "kind": "sbom",
        "path": OUTPUT_RELATIVE,
        "media_type": "application/vnd.cyclonedx+json",
        "license_expression": "CC-BY-4.0",
        "provenance": (
            "Deterministically generated by scripts/generate_engine_e1_sbom.py from "
            "the E1 profile manifest, current native source, and hash-locked declarations"
        ),
        "verification_status": "PASS",
        "vulnerability_analysis_status": "NOT_RUN",
        "note": (
            "CycloneDX source/declaration inventory only; no vulnerability result is claimed"
        ),
    },
}
EXPECTED_ARTIFACT_ORDER = tuple(EXPECTED_ARTIFACTS)
SOURCE_GLOBS = (
    "CMakeLists.txt",
    "CMakePresets.json",
    ".github/workflows/engine-ci.yml",
    "cmake/*.cmake",
    "cmake/*.cmake.in",
    "cmake/*.map",
    "cpp/**/*.h",
    "cpp/**/*.c",
    "cpp/**/*.cc",
    "cpp/**/*.cpp",
    "scripts/bootstrap-engine.sh",
    "scripts/generate_engine_e1_sbom.py",
    "scripts/run-engine-sanitizers.sh",
    "scripts/validate_engine_checkpoint.py",
    "scripts/validate_engine_e0_evidence.py",
    "src/morphoia/compiler.py",
    "tests/native/**/*.c",
    "tests/native/**/*.cc",
    "tests/native/**/*.cpp",
    "tests/native/**/CMakeLists.txt",
    "tests/native/fixtures/*.json",
    "tests/test_engine_evidence.py",
)
SOURCE_LICENSE_RULES = (
    ("CMakeLists.txt", "Apache-2.0 OR MIT"),
    ("CMakePresets.json", "Apache-2.0 OR MIT"),
    (".github/workflows/engine-ci.yml", "Apache-2.0 OR MIT"),
    ("cmake/**", "Apache-2.0 OR MIT"),
    ("cpp/**", "Apache-2.0 OR MIT"),
    ("scripts/bootstrap-engine.sh", "Apache-2.0 OR MIT"),
    ("scripts/generate_engine_e1_sbom.py", "Apache-2.0 OR MIT"),
    ("scripts/run-engine-sanitizers.sh", "Apache-2.0 OR MIT"),
    ("scripts/validate_engine_checkpoint.py", "Apache-2.0 OR MIT"),
    ("scripts/validate_engine_e0_evidence.py", "Apache-2.0 OR MIT"),
    ("src/morphoia/compiler.py", "MIT"),
    ("tests/native/**", "Apache-2.0 OR MIT"),
    ("tests/test_engine_evidence.py", "Apache-2.0 OR MIT"),
)
LOCK_FILES = (
    "requirements/cmake-e0.lock",
    "requirements/engine-ci.lock",
    "requirements/report-ci.lock",
    "requirements/reuse-build-e0.lock",
    "requirements/reuse-e0.lock",
)
LICENSE_FILES = {
    "LICENSE": "MIT",
    "LICENSE-MIT": "MIT",
    "LICENSE-APACHE": "Apache-2.0",
    "LICENSES/Apache-2.0.txt": "Apache-2.0",
    "LICENSES/CC-BY-4.0.txt": "CC-BY-4.0",
    "LICENSES/LicenseRef-Morphoia-Baseline.txt": "LicenseRef-Morphoia-Baseline",
    "LICENSES/LicenseRef-Morphoia-Brand-Assets.txt": "LicenseRef-Morphoia-Brand-Assets",
    "LICENSES/MIT.txt": "MIT",
    "LICENSES/OFL-1.1.txt": "OFL-1.1",
    "NOTICE": "CC-BY-4.0",
}
PACKAGE_RE = re.compile(r"^([A-Za-z0-9_.-]+)==([^\s\\]+)\s*\\?$")
HASH_RE = re.compile(r"^--hash=sha256:([0-9a-f]{64})(?:\s*\\)?$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")


def normalize_package_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def parse_locks(root: Path) -> dict[tuple[str, str], dict[str, set[str]]]:
    packages: dict[tuple[str, str], dict[str, set[str]]] = {}
    for relative in LOCK_FILES:
        path = safe_root_file(root, relative)
        current: tuple[str, str] | None = None
        declaration_has_hash = False
        for number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            package_match = PACKAGE_RE.fullmatch(line)
            if package_match:
                if current is not None and not declaration_has_hash:
                    raise ValueError(
                        f"locked package has no SHA-256 digest before {relative}:{number}"
                    )
                current = (
                    normalize_package_name(package_match.group(1)),
                    package_match.group(2),
                )
                entry = packages.setdefault(current, {"hashes": set(), "locks": set()})
                entry["locks"].add(relative)
                declaration_has_hash = False
                continue
            hash_match = HASH_RE.fullmatch(line)
            if hash_match and current is not None:
                packages[current]["hashes"].add(hash_match.group(1))
                declaration_has_hash = True
                continue
            raise ValueError(f"unsupported lock syntax at {relative}:{number}: {raw_line!r}")
        if current is not None and not declaration_has_hash:
            raise ValueError(f"locked package has no SHA-256 digest at end of {relative}")
    for (name, version), values in packages.items():
        if not values["hashes"]:
            raise ValueError(f"locked package has no SHA-256 digest: {name}=={version}")
    return packages


def collect_source_files(root: Path) -> list[str]:
    values: set[str] = set()
    for pattern in SOURCE_GLOBS:
        for path in root.glob(pattern):
            if path.is_file() and not path.is_symlink():
                values.add(path.relative_to(root).as_posix())
    if not values:
        raise ValueError("E1 native-core profile selected no source files")
    return sorted(values)


def source_license_expression(relative: str) -> str:
    matches = {
        expression
        for pattern, expression in SOURCE_LICENSE_RULES
        if fnmatch.fnmatchcase(relative, pattern)
    }
    if len(matches) != 1:
        raise ValueError(
            f"E1 source path must have exactly one declared license expression: {relative}"
        )
    return next(iter(matches))


def safe_root_file(root: Path, relative: str) -> Path:
    if not isinstance(relative, str):
        raise ValueError("repository path must be a string")  # noqa: TRY004
    posix = PurePosixPath(relative)
    if not relative or posix.is_absolute() or "." in posix.parts or ".." in posix.parts:
        raise ValueError(f"unsafe repository path: {relative!r}")
    resolved_root = root.resolve(strict=True)
    path = resolved_root
    for index, part in enumerate(posix.parts):
        path = path / part
        if path.is_symlink():
            raise ValueError(f"SBOM input path contains a symbolic link: {relative}")
        if index < len(posix.parts) - 1 and not path.is_dir():
            raise ValueError(f"SBOM input has a non-directory component: {relative}")
    if not path.is_file() or path.is_symlink():
        raise ValueError(f"SBOM input is not a regular non-symlink file: {relative}")
    path.resolve(strict=True).relative_to(resolved_root)
    return path


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def component(
    root: Path,
    relative: str,
    bom_ref: str,
    license_expression: str,
    properties: list[dict[str, str]],
) -> dict[str, Any]:
    path = safe_root_file(root, relative)
    return {
        "type": "file",
        "bom-ref": bom_ref,
        "name": relative,
        "hashes": [{"alg": "SHA-256", "content": sha256_file(path)}],
        "licenses": [{"expression": license_expression}],
        "properties": sorted(properties, key=lambda item: (item["name"], item["value"])),
    }


def parse_manifest_text(content: str) -> dict[str, Any]:
    def reject_duplicates(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        value: dict[str, Any] = {}
        for key, item in pairs:
            if key in value:
                raise ValueError(f"duplicate JSON key: {key}")
            value[key] = item
        return value

    def reject_constant(value: str) -> None:
        raise ValueError(f"non-JSON numeric constant: {value}")

    def validate_unicode(value: Any, location: str = "manifest") -> None:
        if isinstance(value, str):
            if any(0xD800 <= ord(character) <= 0xDFFF for character in value):
                raise ValueError(f"lone surrogate in {location}")
        elif isinstance(value, list):
            for index, item in enumerate(value):
                validate_unicode(item, f"{location}[{index}]")
        elif isinstance(value, dict):
            for key, item in value.items():
                validate_unicode(key, f"{location} key")
                validate_unicode(item, f"{location}.{key}")

    manifest = json.loads(
        content,
        object_pairs_hook=reject_duplicates,
        parse_constant=reject_constant,
    )
    if not isinstance(manifest, dict):
        raise ValueError("E1 manifest root must be an object")  # noqa: TRY004
    validate_unicode(manifest)
    return manifest


def validate_manifest_value(root: Path, manifest: dict[str, Any]) -> dict[str, Any]:
    if set(manifest) != MANIFEST_FIELDS:
        raise ValueError(
            "E1 manifest fields differ from the exact schema allow-list: "
            f"{sorted(set(manifest) ^ MANIFEST_FIELDS)}"
        )
    expected_header = {
        "schema_version": "1.0.0",
        "project": "Morphoia Engine",
        "manifest_document_license": MANIFEST_LICENSE,
        "hash_algorithm": "sha256",
    }
    for field, expected in expected_header.items():
        if manifest[field] != expected:
            raise ValueError(f"E1 manifest {field} must be {expected!r}")
    generated_at = manifest["generated_at"]
    if not isinstance(generated_at, str) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", generated_at):
        raise ValueError("E1 manifest generated_at must be YYYY-MM-DD")
    try:
        date.fromisoformat(generated_at)
    except ValueError as error:
        raise ValueError("E1 manifest generated_at is not a calendar date") from error
    artifacts = manifest.get("artifacts")
    if not isinstance(artifacts, list) or len(artifacts) != len(EXPECTED_ARTIFACTS):
        raise ValueError("E1 manifest must contain exactly the three profile artifacts")
    identifiers = [artifact.get("id") if isinstance(artifact, dict) else None for artifact in artifacts]
    if identifiers != list(EXPECTED_ARTIFACT_ORDER):
        raise ValueError("E1 manifest artifact order or identifiers differ from the exact profile")
    paths: set[str] = set()
    for artifact in artifacts:
        if not isinstance(artifact, dict):
            raise ValueError("E1 manifest artifact must be an object")  # noqa: TRY004
        identifier = artifact.get("id")
        expected_identity = EXPECTED_ARTIFACTS.get(identifier)
        if expected_identity is None:
            raise ValueError(f"E1 manifest contains an artifact outside the profile: {identifier}")
        expected_fields = {"id", "size_bytes", "sha256", *expected_identity}
        if set(artifact) != expected_fields:
            raise ValueError(
                f"E1 artifact {identifier} fields differ from the exact profile: "
                f"{sorted(set(artifact) ^ expected_fields)}"
            )
        for field, expected in expected_identity.items():
            if artifact.get(field) != expected:
                raise ValueError(
                    f"E1 artifact {identifier} {field} must be {expected!r}"
                )
        relative = artifact.get("path")
        if not isinstance(relative, str) or relative in paths:
            raise ValueError("E1 manifest contains a missing or duplicate artifact path")
        paths.add(relative)
        expected_hash = artifact.get("sha256")
        if not isinstance(expected_hash, str) or not SHA256_RE.fullmatch(expected_hash):
            raise ValueError(f"E1 artifact {identifier} has an invalid SHA-256")
        expected_size = artifact.get("size_bytes")
        if (
            not isinstance(expected_size, int)
            or isinstance(expected_size, bool)
            or not 0 <= expected_size <= SAFE_INTEGER_MAX
        ):
            raise ValueError(f"E1 artifact {identifier} has an invalid size")
        if identifier == SELF_ARTIFACT_ID:
            continue
        source = safe_root_file(root, relative)
        if sha256_file(source) != expected_hash or source.stat().st_size != expected_size:
            raise ValueError(f"E1 artifact {identifier} digest or size differs from {relative}")
    return manifest


def exact_repository_argument(root: Path, path: Path, expected_relative: str) -> Path:
    resolved_root = root.resolve(strict=True)
    expected = resolved_root / expected_relative
    candidate = Path(os.path.abspath(path))
    if candidate != expected:
        raise ValueError(f"path must be exactly {expected_relative}")
    return expected


def read_manifest(root: Path, path: Path) -> dict[str, Any]:
    manifest_path = exact_repository_argument(root, path, MANIFEST_RELATIVE)
    manifest_path = safe_root_file(root, MANIFEST_RELATIVE)
    metadata = os.stat(manifest_path, follow_symlinks=False)
    if metadata.st_nlink != 1:
        raise ValueError("E1 manifest must not be a hard-link alias")
    return validate_manifest_value(root, parse_manifest_text(manifest_path.read_text(encoding="utf-8")))


def self_artifact(manifest: dict[str, Any]) -> dict[str, Any]:
    return next(item for item in manifest["artifacts"] if item["id"] == SELF_ARTIFACT_ID)


def build_bom(root: Path, manifest_path: Path) -> dict[str, Any]:
    root = root.resolve()
    manifest = read_manifest(root, manifest_path)
    packages = parse_locks(root)
    components: list[dict[str, Any]] = []

    for artifact in manifest["artifacts"]:
        if artifact["id"] == SELF_ARTIFACT_ID:
            continue
        components.append(
            component(
                root,
                artifact["path"],
                f"urn:morphoia:artifact:{artifact['id']}",
                artifact["license_expression"],
                [
                    {"name": "morphoia:artifact:id", "value": artifact["id"]},
                    {"name": "morphoia:artifact:kind", "value": artifact["kind"]},
                    {
                        "name": "morphoia:evidence:verification-status",
                        "value": artifact["verification_status"],
                    },
                ],
            )
        )
    for relative, expression in sorted(LICENSE_FILES.items()):
        components.append(
            component(
                root,
                relative,
                f"urn:morphoia:license-file:{urllib.parse.quote(relative, safe='')}",
                expression,
                [{"name": "morphoia:role", "value": "license-or-notice-file"}],
            )
        )
    for relative in LOCK_FILES:
        components.append(
            component(
                root,
                relative,
                f"urn:morphoia:lock:{urllib.parse.quote(relative, safe='')}",
                "Apache-2.0 OR MIT",
                [
                    {"name": "morphoia:profile", "value": PROFILE},
                    {"name": "morphoia:role", "value": "hashed-python-lock"},
                ],
            )
        )
    for relative in collect_source_files(root):
        components.append(
            component(
                root,
                relative,
                f"urn:morphoia:e1-native-source:{urllib.parse.quote(relative, safe='')}",
                source_license_expression(relative),
                [{"name": "morphoia:role", "value": "native-source"}],
            )
        )
    for (name, version), values in sorted(packages.items()):
        purl = f"pkg:pypi/{urllib.parse.quote(name)}@{urllib.parse.quote(version)}"
        components.append(
            {
                "type": "library",
                "bom-ref": purl,
                "name": name,
                "version": version,
                "scope": "excluded",
                "purl": purl,
                "hashes": [
                    {"alg": "SHA-256", "content": digest}
                    for digest in sorted(values["hashes"])
                ],
                "licenses": [{"license": {"name": "NOASSERTION"}}],
                "properties": [
                    {"name": "morphoia:license-review-status", "value": "NOT_RUN"},
                    {
                        "name": "morphoia:provisioning",
                        "value": "lock-only-not-redistributed-by-sbom",
                    },
                    {"name": "morphoia:source-locks", "value": ",".join(sorted(values["locks"]))},
                ],
            }
        )

    components.sort(key=lambda item: item["bom-ref"])
    seed = json.dumps(
        {
            "profile": PROFILE,
            "version": PROJECT_VERSION,
            "components": [
                {
                    "bom-ref": item["bom-ref"],
                    "hashes": item.get("hashes", []),
                    "version": item.get("version"),
                }
                for item in components
            ],
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    root_ref = f"pkg:generic/morphoia-engine@{PROJECT_VERSION}?profile={PROFILE}"
    return {
        "bomFormat": "CycloneDX",
        "specVersion": "1.5",
        "serialNumber": f"urn:uuid:{uuid.uuid5(uuid.NAMESPACE_URL, seed)}",
        "version": 1,
        "metadata": {
            "component": {
                "type": "application",
                "bom-ref": root_ref,
                "group": "org.morphoia",
                "name": "morphoia-engine",
                "version": PROJECT_VERSION,
                "licenses": [{"expression": "Apache-2.0 OR MIT"}],
                "externalReferences": [
                    {"type": "vcs", "url": "https://github.com/Aminoside/morphoia"}
                ],
                "properties": [
                    {"name": "morphoia:profile", "value": PROFILE},
                    {"name": "morphoia:sbom-content", "value": "source-and-declared-tools"},
                    {"name": "morphoia:vulnerability-analysis-status", "value": "NOT_RUN"},
                    {
                        "name": "morphoia:vulnerability-analysis-note",
                        "value": "Inventory generation is not a vulnerability assessment",
                    },
                ],
            }
        },
        "components": components,
        "dependencies": [
            {"ref": root_ref, "dependsOn": []},
            *({"ref": item["bom-ref"], "dependsOn": []} for item in components),
        ],
    }


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def profile_input_paths(root: Path, manifest: dict[str, Any]) -> list[str]:
    paths = {
        MANIFEST_RELATIVE,
        *LICENSE_FILES,
        *LOCK_FILES,
        *collect_source_files(root),
        *(
            artifact["path"]
            for artifact in manifest["artifacts"]
            if artifact["id"] != SELF_ARTIFACT_ID
        ),
    }
    paths.discard(OUTPUT_RELATIVE)
    return sorted(paths)


def open_parent_directory(root: Path, relative: str) -> tuple[int, str]:
    posix = PurePosixPath(relative)
    if posix.is_absolute() or "." in posix.parts or ".." in posix.parts or len(posix.parts) < 2:
        raise ValueError(f"unsafe output path: {relative!r}")
    flags = os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC | os.O_NOFOLLOW
    descriptor = os.open(root.resolve(strict=True), flags)
    try:
        for part in posix.parts[:-1]:
            child = os.open(part, flags, dir_fd=descriptor)
            os.close(descriptor)
            descriptor = child
        return descriptor, posix.name
    except BaseException:
        os.close(descriptor)
        raise


def snapshot_output(
    root: Path, parent_descriptor: int, output_name: str, input_paths: list[str]
) -> tuple[int, int, int, int] | None:
    try:
        output_metadata = os.stat(
            output_name, dir_fd=parent_descriptor, follow_symlinks=False
        )
    except FileNotFoundError:
        return None
    if not stat.S_ISREG(output_metadata.st_mode):
        raise ValueError("E1 SBOM output must be a regular non-symlink file")
    output_identity = (output_metadata.st_dev, output_metadata.st_ino)
    for relative in input_paths:
        input_metadata = os.stat(safe_root_file(root, relative), follow_symlinks=False)
        if (input_metadata.st_dev, input_metadata.st_ino) == output_identity:
            raise ValueError(f"E1 SBOM output aliases input file {relative}")
    if output_metadata.st_nlink != 1:
        raise ValueError("E1 SBOM output must have exactly one hard link")
    return (
        output_metadata.st_dev,
        output_metadata.st_ino,
        stat.S_IFMT(output_metadata.st_mode),
        output_metadata.st_nlink,
    )


def verify_output_unchanged(
    parent_descriptor: int,
    output_name: str,
    expected: tuple[int, int, int, int] | None,
) -> None:
    try:
        metadata = os.stat(
            output_name, dir_fd=parent_descriptor, follow_symlinks=False
        )
    except FileNotFoundError:
        if expected is None:
            return
        raise ValueError("E1 SBOM output disappeared during atomic generation") from None
    if not stat.S_ISREG(metadata.st_mode) or metadata.st_nlink != 1:
        raise ValueError("E1 SBOM output became an unsafe file before publication")
    actual = (
        metadata.st_dev,
        metadata.st_ino,
        stat.S_IFMT(metadata.st_mode),
        metadata.st_nlink,
    )
    if expected is None or actual != expected:
        raise ValueError("E1 SBOM output changed during atomic generation")


def read_output_exact(root: Path, relative: str, input_paths: list[str]) -> bytes:
    if relative != OUTPUT_RELATIVE:
        raise ValueError(f"output path must be exactly {OUTPUT_RELATIVE}")
    parent_descriptor, output_name = open_parent_directory(root, relative)
    descriptor = -1
    try:
        snapshot_output(root, parent_descriptor, output_name, input_paths)
        descriptor = os.open(
            output_name,
            os.O_RDONLY | os.O_CLOEXEC | os.O_NOFOLLOW,
            dir_fd=parent_descriptor,
        )
        metadata = os.fstat(descriptor)
        if not stat.S_ISREG(metadata.st_mode):
            raise ValueError("E1 SBOM output must be a regular file")
        chunks: list[bytes] = []
        while True:
            chunk = os.read(descriptor, 1024 * 1024)
            if not chunk:
                return b"".join(chunks)
            chunks.append(chunk)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        os.close(parent_descriptor)


def write_atomic(
    root: Path,
    relative: str,
    content: bytes,
    input_paths: list[str],
    before_replace: Callable[[], None] | None = None,
) -> None:
    if relative != OUTPUT_RELATIVE:
        raise ValueError(f"output path must be exactly {OUTPUT_RELATIVE}")
    parent_descriptor, output_name = open_parent_directory(root, relative)
    temporary_name: str | None = None
    descriptor = -1
    try:
        initial_output = snapshot_output(
            root, parent_descriptor, output_name, input_paths
        )
        for _ in range(64):
            candidate = f".{output_name}.{secrets.token_hex(12)}.tmp"
            try:
                descriptor = os.open(
                    candidate,
                    os.O_WRONLY
                    | os.O_CREAT
                    | os.O_EXCL
                    | os.O_CLOEXEC
                    | os.O_NOFOLLOW,
                    0o600,
                    dir_fd=parent_descriptor,
                )
                temporary_name = candidate
                break
            except FileExistsError:
                continue
        if descriptor < 0 or temporary_name is None:
            raise OSError("cannot allocate unique E1 SBOM temporary file")
        view = memoryview(content)
        while view:
            written = os.write(descriptor, view)
            if written <= 0:
                raise OSError("short write while generating E1 SBOM")
            view = view[written:]
        os.fchmod(descriptor, 0o644)
        os.fsync(descriptor)
        os.close(descriptor)
        descriptor = -1
        if before_replace is not None:
            before_replace()
        verify_output_unchanged(parent_descriptor, output_name, initial_output)
        os.replace(
            temporary_name,
            output_name,
            src_dir_fd=parent_descriptor,
            dst_dir_fd=parent_descriptor,
        )
        temporary_name = None
        os.fsync(parent_descriptor)
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        if temporary_name is not None:
            try:
                os.unlink(temporary_name, dir_fd=parent_descriptor)
                os.fsync(parent_descriptor)
            except FileNotFoundError:
                pass
        os.close(parent_descriptor)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--manifest", type=Path, default=Path("artifacts/e1/manifest.json"))
    parser.add_argument(
        "--output", type=Path, default=Path("artifacts/sbom/engine-e1-native-core.cdx.json")
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(sys.argv[1:] if argv is None else argv)
    root = arguments.root.resolve(strict=True)
    manifest = arguments.manifest if arguments.manifest.is_absolute() else root / arguments.manifest
    output = arguments.output if arguments.output.is_absolute() else root / arguments.output
    try:
        exact_repository_argument(root, manifest, MANIFEST_RELATIVE)
        exact_repository_argument(root, output, OUTPUT_RELATIVE)
        manifest_value = read_manifest(root, manifest)
        self_entry = self_artifact(manifest_value)
        content = canonical_json(build_bom(root, manifest))
        encoded = content.encode("utf-8")
        input_paths = profile_input_paths(root, manifest_value)
        digest = hashlib.sha256(encoded).hexdigest()
        if self_entry["sha256"] != digest or self_entry["size_bytes"] != len(encoded):
            raise ValueError(
                "E1 manifest self-artifact hash or size differs from deterministic output"
            )
        if arguments.check:
            if read_output_exact(root, OUTPUT_RELATIVE, input_paths) != encoded:
                print(f"FAIL: E1 SBOM differs from deterministic output: {output}", file=sys.stderr)
                return 1
        else:
            write_atomic(root, OUTPUT_RELATIVE, encoded, input_paths)
    except (OSError, ValueError, RuntimeError) as error:
        print(f"FAIL: {error}", file=sys.stderr)
        return 1
    print(f"PASS: E1 {PROFILE} CycloneDX SBOM sha256:{digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
